This simulation is for a flat dispersion line at 30meV from a single crystal.  The beam used is a 200meV beam simulated with 1e9 neutrons.

In [1]:
%matplotlib notebook
from matplotlib import pyplot as plt
import numpy as np
import histogram.hdf as hh, histogram as H

In [2]:
# Define which directory to use for my simulation (will change name to 30meV dispersion)
workdir = "/SNS/users/p63/mcvine/research/single-flat-dispersions/200meV_beam_5meV_dispersion/"

In [3]:
# change into primary simulation directory
%cd {workdir}
!ls

/SNS/users/p63/mcvine/research/single-flat-dispersions/200meV_beam_5meV_dispersion
single-flat-dispersion-width-simulation.ipynb


In [4]:
!source ~lj7/.use-miniconda2
!source activate mcvine

discarding /SNS/users/lj7/software/miniconda2/envs/mcvine/bin from PATH
prepending /SNS/users/lj7/software/miniconda2/envs/mcvine/bin to PATH


In [ ]:
!cp -r 10meV_beam_5meV_dispersion_INCOMPLETE/samples 200meV_beam_5meV_dispersion/samples

In [5]:
%cd "{workdir}/samples/X/sampleassembly"

/SNS/users/p63/mcvine/research/single-flat-dispersions/200meV_beam_5meV_dispersion/samples/X/sampleassembly


In [6]:
!cat X.xyz

8
5 0 0    0 5 0    0 0 5
V 0 0 0
V 0 0 0
V 0 0 0
V 0 0 0
V 0 0 0
V 0 0 0
V 0 0 0
V 0 0 0

In [7]:
%%file ./X.xyz
8
5 0 0    0 5 0    0 0 5
V 0 0 0
V 0 0 0
V 0 0 0
V 0 0 0
V 0 0 0
V 0 0 0
V 0 0 0
V 0 0 0

Overwriting ./X.xyz


In [8]:
!cat X.xyz

8
5 0 0    0 5 0    0 0 5
V 0 0 0
V 0 0 0
V 0 0 0
V 0 0 0
V 0 0 0
V 0 0 0
V 0 0 0
V 0 0 0

In [7]:
!cat X-scatterer.xml

<?xml version="1.0"?>

<!DOCTYPE scatterer>

<!-- weights: absorption, scattering, transmission -->
<homogeneous_scatterer 
    mcweights="0, 1, 0.1"
    max_multiplescattering_loops="3"
    >
  
 <KernelContainer average="yes">

  <E_vQ_Kernel 
     E_Q="5.0" 
     S_Q="1"
     Emax="10*meV"
    orientation="0.894427191,0.0,-0.4472135955,0.0,1.0,0.0,0.4472135955,0.0,0.894427191"
    />
    
 </KernelContainer>
  
</homogeneous_scatterer>

In [10]:
%%file X-scatterer.xml
<?xml version="1.0"?>

<!DOCTYPE scatterer>

<!-- weights: absorption, scattering, transmission -->
<homogeneous_scatterer 
    mcweights="0, 1, 0.1"
    max_multiplescattering_loops="3"
    >
  
 <KernelContainer average="yes">

  <E_vQ_Kernel 
     E_Q="5.0" 
     S_Q="1"
     Emax="10*meV"
    />
    
 </KernelContainer>
  
</homogeneous_scatterer>

Overwriting X-scatterer.xml


In [11]:
a,b,c=5,5,5

from numpy import sin, cos, deg2rad
a1 = [a, 0, 0]
a2 = [0, b, 0]
a3 = [0, 0, c]

twopi = 2*np.pi
f = twopi/np.dot(a1, np.cross(a2, a3))
b1 = np.cross(a2,a3) * f
b2 = np.cross(a3,a1) * f
b3 = np.cross(a1,a2) * f
b1,b2,b3

(array([ 1.25663706,  0.        ,  0.        ]),
 array([ 0.        ,  1.25663706,  0.        ]),
 array([ 0.        ,  0.        ,  1.25663706]))

In [12]:
ez = b1 + 2*b3; ez /= np.linalg.norm(ez)
ex1 = b1
ey = np.cross(ez, ex1); ey/=np.linalg.norm(ey)
ex = np.cross(ey, ez)
ex, ey, ez

(array([ 0.89442719,  0.        , -0.4472136 ]),
 array([ 0.,  1.,  0.]),
 array([ 0.4472136 ,  0.        ,  0.89442719]))

In [13]:
R = np.array([ ex, ey, ez ])
Rflat = R.copy(); Rflat.shape = -1,
R, Rflat

(array([[ 0.89442719,  0.        , -0.4472136 ],
        [ 0.        ,  1.        ,  0.        ],
        [ 0.4472136 ,  0.        ,  0.89442719]]),
 array([ 0.89442719,  0.        , -0.4472136 ,  0.        ,  1.        ,
         0.        ,  0.4472136 ,  0.        ,  0.89442719]))

In [14]:
'orientation="%s"' % (','.join(str(e) for e in Rflat),)

'orientation="0.894427191,0.0,-0.4472135955,0.0,1.0,0.0,0.4472135955,0.0,0.894427191"'

In [15]:
# modify X-scatterer.xml to specify the orientation

In [8]:
%%file X-scatterer.xml
<?xml version="1.0"?>

<!DOCTYPE scatterer>

<!-- weights: absorption, scattering, transmission -->
<homogeneous_scatterer 
    mcweights="0, 1, 0.1"
    max_multiplescattering_loops="3"
    >
  
 <KernelContainer average="yes">

  <E_vQ_Kernel 
     E_Q="30.0" 
     S_Q="1"
     Emax="60*meV"
    orientation="0.894427191,0.0,-0.4472135955,0.0,1.0,0.0,0.4472135955,0.0,0.894427191"
    />
    
 </KernelContainer>
  
</homogeneous_scatterer>

Overwriting X-scatterer.xml


In [17]:
!cat X-scatterer.xml

<?xml version="1.0"?>

<!DOCTYPE scatterer>

<!-- weights: absorption, scattering, transmission -->
<homogeneous_scatterer 
    mcweights="0, 1, 0.1"
    max_multiplescattering_loops="3"
    >
  
 <KernelContainer average="yes">

  <E_vQ_Kernel 
     E_Q="5.0" 
     S_Q="1"
     Emax="10*meV"
    orientation="0.894427191,0.0,-0.4472135955,0.0,1.0,0.0,0.4472135955,0.0,0.894427191"
    />
    
 </KernelContainer>
  
</homogeneous_scatterer>

In [9]:
!cat sampleassembly.xml

<SampleAssembly name="X">

    <PowderSample name="X" type="sample">
        <Shape>
            <cylinder radius="5*mm" height="20*mm"/>
        </Shape>
        <Phase type="crystal">
            <ChemicalFormula>Fe</ChemicalFormula>
            <xyzfile>X.xyz</xyzfile>
        </Phase>
    </PowderSample>
    
    <LocalGeometer registry-coordinate-system="InstrumentScientist">
        <Register name="X" position="(0,0,0)" orientation="(0,0,0)"/>
    </LocalGeometer>

</SampleAssembly>

In [10]:
!ls

sampleassembly.xml  X-scatterer.xml  X.xyz


In [11]:
%cd {workdir}

/SNS/users/p63/mcvine/research/single-flat-dispersions/200meV_beam_5meV_dispersion


In [12]:
!ls

samples  single-flat-dispersion-width-simulation.ipynb


In [13]:
!mkdir scattering
%cd scattering

/SNS/users/p63/mcvine/research/single-flat-dispersions/200meV_beam_5meV_dispersion/scattering


In [14]:
!rsync -a ~lj7/simulations/mcvine_workflow/DGS/ARCS/single-crystal/* ./
!ls

scripts  template


In [15]:
!ln -s ../../../beams/beam_200meV_1e9_neutrons/ beam
!ls -l

total 4
lrwxrwxrwx 1 p63 users   40 Jul 20 14:25 beam -> ../../../beams/beam_200meV_1e9_neutrons/
drwxrwxr-x 5 p63 users  152 Jun  7 22:32 scripts
drwxr-xr-x 2 p63 users 4096 Jun  7 22:32 template


In [16]:
%cd template

!ln -s ../../samples/X/sampleassembly

!ln -s ../beam

%cd ..

/SNS/users/p63/mcvine/research/single-flat-dispersions/200meV_beam_5meV_dispersion/scattering/template
/SNS/users/p63/mcvine/research/single-flat-dispersions/200meV_beam_5meV_dispersion/scattering


In [17]:
%%file sim.yml

cluster:
  nodes: 10
instrument:
  name: arcs
scatter:
  ncount: 1e6
  multiple_scattering: off
  template: ./template


Writing sim.yml


In [19]:
# Test the simulation for a single angle
#!./scripts/sim.py --angle=30.0

In [18]:
%%file sim.yml

cluster:
  nodes: 10
instrument:
  name: arcs
scatter:
  ncount: 1e6
  multiple_scattering: off
  template: ./template

Overwriting sim.yml


In [20]:
%%file create-submit.py
import numpy as np
ostream = open('submit.sh', 'wt')
for a in np.arange(-60, 60.1, 1.):
    ostream.write('./scripts/sim.py --angle=%s \n' % a)
    continue
ostream.close()

Writing create-submit.py


In [21]:
!cat create-submit.py

import numpy as np
ostream = open('submit.sh', 'wt')
for a in np.arange(-60, 60.1, 1.):
    ostream.write('./scripts/sim.py --angle=%s \n' % a)
    continue
ostream.close()

In [22]:
# run the script to create submit.sh
!python ./create-submit.py

In [23]:
# make sure submit.sh is executable
!chmod +x submit.sh
# and then start it script in the background

In [24]:
%%script bash --bg
./submit.sh
# this will take a while to finish.

Starting job # 0 in a separate thread.


## Reduction

In [25]:
%cd "{workdir}/scattering"
!ls

/SNS/users/p63/mcvine/research/single-flat-dispersions/200meV_beam_5meV_dispersion/scattering
beam		  work_16.0   work_26.0   work_36.0   work_46.0   work_56.0
create-submit.py  work_-17.0  work_-27.0  work_-37.0  work_-47.0  work_-57.0
scripts		  work_17.0   work_27.0   work_37.0   work_47.0   work_57.0
sim.yml		  work_-18.0  work_-28.0  work_-38.0  work_-48.0  work_-58.0
submit.sh	  work_18.0   work_28.0   work_38.0   work_48.0   work_58.0
template	  work_-19.0  work_-29.0  work_-39.0  work_-49.0  work_-59.0
work_0.0	  work_19.0   work_29.0   work_39.0   work_49.0   work_59.0
work_-1.0	  work_-2.0   work_-3.0   work_-4.0   work_-5.0   work_-6.0
work_1.0	  work_2.0    work_3.0	  work_4.0    work_5.0	  work_6.0
work_-10.0	  work_-20.0  work_-30.0  work_-40.0  work_-50.0  work_-60.0
work_10.0	  work_20.0   work_30.0   work_40.0   work_50.0   work_60.0
work_-11.0	  work_-21.0  work_-31.0  work_-41.0  work_-51.0  work_-7.0
work_11.0	  work_21.0   work_31.0   work_41.0   work_51.0   work_7

In [26]:
# reduce tof events to E events
# this takes a long time!
!./scripts/reduce/reduceKeepingEvents_batch.py -60,60.1,1. 200 0,200,0.5 > log.reduce