In [1]:
%matplotlib notebook
from matplotlib import pyplot as plt
import numpy as np
import histogram.hdf as hh, histogram as H

In [2]:
# Define which directory to use for my simulation
workdir = "/SNS/users/p63/mcvine/research/single-flat-dispersions/10meV_beam_5meV_dispersion/"

In [3]:
# change into primary simulation directory
%cd {workdir}
!ls

/SNS/users/p63/mcvine/research/single-flat-dispersions/10meV_beam_5meV_dispersion
samples  Untitled.ipynb


In [4]:
!source ~lj7/.use-miniconda2
!source activate mcvine

discarding /SNS/users/lj7/software/miniconda2/envs/mcvine/bin from PATH
prepending /SNS/users/lj7/software/miniconda2/envs/mcvine/bin to PATH


In [5]:
%cd "{workdir}/samples/X/sampleassembly"

/SNS/users/p63/mcvine/research/single-flat-dispersions/10meV_beam_5meV_dispersion/samples/X/sampleassembly


In [6]:
!cat X.xyz

8
3 0 0    0 3 0    0 0 3
V 0 0 0
V 0 0 0
V 0 0 0
V 0 0 0
V 0 0 0
V 0 0 0
V 0 0 0
V 0 0 0

In [7]:
%%file ./X.xyz
8
5 0 0    0 5 0    0 0 5
V 0 0 0
V 0 0 0
V 0 0 0
V 0 0 0
V 0 0 0
V 0 0 0
V 0 0 0
V 0 0 0

Overwriting ./X.xyz


In [8]:
!cat X.xyz

8
5 0 0    0 5 0    0 0 5
V 0 0 0
V 0 0 0
V 0 0 0
V 0 0 0
V 0 0 0
V 0 0 0
V 0 0 0
V 0 0 0

In [9]:
!cat X-scatterer.xml

<?xml version="1.0"?>

<!DOCTYPE scatterer>

<!-- weights: absorption, scattering, transmission -->
<homogeneous_scatterer 
    mcweights="0, 1, 0.1"
    max_multiplescattering_loops="3"
    >
  
 <KernelContainer average="yes">

  <E_Q_Kernel 
     E_Q="5.0" 
     S_Q="1"
     Qmin="0./angstrom"
     Qmax="18/angstrom"
    />
    
 </KernelContainer>
  
</homogeneous_scatterer>


In [10]:
%%file X-scatterer.xml
<?xml version="1.0"?>

<!DOCTYPE scatterer>

<!-- weights: absorption, scattering, transmission -->
<homogeneous_scatterer 
    mcweights="0, 1, 0.1"
    max_multiplescattering_loops="3"
    >
  
 <KernelContainer average="yes">

  <E_vQ_Kernel 
     E_Q="5.0" 
     S_Q="1"
     Emax="10*meV"
    />
    
 </KernelContainer>
  
</homogeneous_scatterer>

Overwriting X-scatterer.xml


In [11]:
a,b,c=5,5,5

from numpy import sin, cos, deg2rad
a1 = [a, 0, 0]
a2 = [0, b, 0]
a3 = [0, 0, c]

twopi = 2*np.pi
f = twopi/np.dot(a1, np.cross(a2, a3))
b1 = np.cross(a2,a3) * f
b2 = np.cross(a3,a1) * f
b3 = np.cross(a1,a2) * f
b1,b2,b3

(array([ 1.25663706,  0.        ,  0.        ]),
 array([ 0.        ,  1.25663706,  0.        ]),
 array([ 0.        ,  0.        ,  1.25663706]))

In [12]:
ez = b1 + 2*b3; ez /= np.linalg.norm(ez)
ex1 = b1
ey = np.cross(ez, ex1); ey/=np.linalg.norm(ey)
ex = np.cross(ey, ez)
ex, ey, ez

(array([ 0.89442719,  0.        , -0.4472136 ]),
 array([ 0.,  1.,  0.]),
 array([ 0.4472136 ,  0.        ,  0.89442719]))

In [13]:
R = np.array([ ex, ey, ez ])
Rflat = R.copy(); Rflat.shape = -1,
R, Rflat

(array([[ 0.89442719,  0.        , -0.4472136 ],
        [ 0.        ,  1.        ,  0.        ],
        [ 0.4472136 ,  0.        ,  0.89442719]]),
 array([ 0.89442719,  0.        , -0.4472136 ,  0.        ,  1.        ,
         0.        ,  0.4472136 ,  0.        ,  0.89442719]))

In [14]:
'orientation="%s"' % (','.join(str(e) for e in Rflat),)

'orientation="0.894427191,0.0,-0.4472135955,0.0,1.0,0.0,0.4472135955,0.0,0.894427191"'

In [15]:
# modify X-scatterer.xml to specify the orientation

In [16]:
%%file X-scatterer.xml
<?xml version="1.0"?>

<!DOCTYPE scatterer>

<!-- weights: absorption, scattering, transmission -->
<homogeneous_scatterer 
    mcweights="0, 1, 0.1"
    max_multiplescattering_loops="3"
    >
  
 <KernelContainer average="yes">

  <E_vQ_Kernel 
     E_Q="5.0" 
     S_Q="1"
     Emax="10*meV"
    orientation="0.894427191,0.0,-0.4472135955,0.0,1.0,0.0,0.4472135955,0.0,0.894427191"
    />
    
 </KernelContainer>
  
</homogeneous_scatterer>

Overwriting X-scatterer.xml


In [17]:
!cat X-scatterer.xml

<?xml version="1.0"?>

<!DOCTYPE scatterer>

<!-- weights: absorption, scattering, transmission -->
<homogeneous_scatterer 
    mcweights="0, 1, 0.1"
    max_multiplescattering_loops="3"
    >
  
 <KernelContainer average="yes">

  <E_vQ_Kernel 
     E_Q="5.0" 
     S_Q="1"
     Emax="10*meV"
    orientation="0.894427191,0.0,-0.4472135955,0.0,1.0,0.0,0.4472135955,0.0,0.894427191"
    />
    
 </KernelContainer>
  
</homogeneous_scatterer>

In [18]:
!cat sampleassembly.xml

<SampleAssembly name="X">

    <PowderSample name="X" type="sample">
        <Shape>
            <cylinder radius="5*mm" height="20*mm"/>
        </Shape>
        <Phase type="crystal">
            <ChemicalFormula>Fe</ChemicalFormula>
            <xyzfile>X.xyz</xyzfile>
        </Phase>
    </PowderSample>
    
    <LocalGeometer registry-coordinate-system="InstrumentScientist">
        <Register name="X" position="(0,0,0)" orientation="(0,0,0)"/>
    </LocalGeometer>

</SampleAssembly>

In [19]:
!ls

sampleassembly.xml  X-scatterer.xml  X.xyz


In [20]:
%cd {workdir}

/SNS/users/p63/mcvine/research/single-flat-dispersions/10meV_beam_5meV_dispersion


In [21]:
!ls

samples  single flat dispersion width simulation.ipynb


In [22]:
!mkdir scattering
%cd scattering

/SNS/users/p63/mcvine/research/single-flat-dispersions/10meV_beam_5meV_dispersion/scattering


In [23]:
!rsync -a ~lj7/simulations/mcvine_workflow/DGS/ARCS/single-crystal/* ./
!ls

scripts  template


In [24]:
!ln -s ../../../beams/beam_10meV_1e9_neutrons/ beam
!ls -l

total 4
lrwxrwxrwx 1 p63 users   39 Jul 14 11:32 beam -> ../../../beams/beam_10meV_1e9_neutrons/
drwxrwxr-x 5 p63 users  152 Jun  7 22:32 scripts
drwxr-xr-x 2 p63 users 4096 Jun  7 22:32 template


In [25]:
%cd template

!ln -s ../../samples/X/sampleassembly

!ln -s ../beam

%cd ..

/SNS/users/p63/mcvine/research/single-flat-dispersions/10meV_beam_5meV_dispersion/scattering/template
/SNS/users/p63/mcvine/research/single-flat-dispersions/10meV_beam_5meV_dispersion/scattering


In [26]:
%%file sim.yml

cluster:
  nodes: 15
instrument:
  name: arcs
scatter:
  ncount: 1e6
  multiple_scattering: off
  template: ./template


Writing sim.yml


In [27]:
# Test the simulation for a single angle
!./scripts/sim.py --angle=30.0

SAMPLE_ANGLE=30.0 time ./scatter &> log.scatter
time ./create-nxs &> log.create-nxs

real	1m30.005s
user	15m39.137s
sys	3m22.509s
cp sim.nxs sim-30.0.nxs
mcvine instruments arcs nxs populate_metadata --type=Ei --beam_outdir=beam/out --nxs=sim-30.0.nxs
/SNS/users/lj7/software/miniconda2/envs/mcvine/lib/python2.7/site-packages/mcvine/deployment_info.py:41: UserWarning: Neither environment variable MCVINE_DIR nor DANSE_DIR was defined. Assumed that it is /SNS/users/lj7/software/miniconda2/envs/mcvine.
  warnings.warn(msg)


In [28]:
%%file sim.yml

cluster:
  nodes: 10
instrument:
  name: arcs
scatter:
  ncount: 1e8
  multiple_scattering: off
  template: ./template

Overwriting sim.yml


In [29]:
%%file create-submit.py
import numpy as np
ostream = open('submit.sh', 'wt')
for a in np.arange(-90, 90.1, 3.):
    ostream.write('./scripts/sim.py --angle=%s \n' % a)
    continue
ostream.close()

Writing create-submit.py


In [30]:
!cat create-submit.py

import numpy as np
ostream = open('submit.sh', 'wt')
for a in np.arange(-90, 90.1, 3.):
    ostream.write('./scripts/sim.py --angle=%s \n' % a)
    continue
ostream.close()

In [31]:
# run the script to create submit.sh
!python ./create-submit.py

In [32]:
# make sure submit.sh is executable
!chmod +x submit.sh
# and then start it script in the background

In [33]:
%%script bash --bg
./submit.sh
# this will take a while to finish.

Starting job # 0 in a separate thread.
